ALTER TABLE current_available_products
DROP CONSTRAINT IF EXISTS current_available_products_pkey;

ALTER TABLE current_available_products
    RENAME COLUMN id TO text_id;

-- 2) Добавим новый автогенерируемый id
ALTER TABLE current_available_products
    ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 3) Сделаем новый id первичным ключом
ALTER TABLE current_available_products
    ADD CONSTRAINT current_available_products_pkey PRIMARY KEY (id);